version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file:
      - .env

  django:
    environment:
      - PYTHONPATH=/app/openbadge-server
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - USE_DOCKER=yes
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ../data:/data
    ports:
      - "8000:8000"
    links:
      - postgres





